# Generated by Django 5.2 on 2025-06-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_usuario_imagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='filme',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
    ]
